name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Change this to your branch name if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Make sure this matches your Node version

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # Change this if your build script is different

    - name: Deploy to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: npx netlify deploy --prod --dir=public  # Change "public" to your build output directory if different
